Fix  node-ds.yaml kubeletDir
kubesphere/helm-charts pull request #192
Opened 2021-11-12 02:04 UTC by k8sre

2021-11-15 03:02 UTC, zheng1 commented
/cc @stoneshi-yunify @dkeven

2021-11-15 03:08 UTC, dkeven requested changes
Thanks for your PR, could you also bump the chart version to a newer one?

2021-11-15 03:09 UTC, stoneshi-yunify reviewed
/lgtm

2021-11-24 02:06 UTC, zheng1 commented
Hi, @k8sre , please update the version in Chart.yaml

2021-11-25 05:29 UTC, dkeven commented
/lgtm

2021-11-25 05:56 UTC, zheng1 commented
/approve

2021-11-25 05:59 UTC, merged