Upload pvc-autoresizer
kubesphere/helm-charts pull request #205
Opened 2021-12-21 07:23 UTC by f10atin9

Signed-off-by: f10atin9 <f10atin9@kubesphere.io>

2021-12-21 07:44 UTC, f10atin9 commented
/assign @stoneshi-yunify @zhengyi1

2021-12-21 09:56 UTC, stoneshi-yunify requested changes

2021-12-21 09:56 UTC, stoneshi-yunify commented on src/main/pvc-autoresizer/values.yaml
> +  repository: f10atin9/pvc-autoresizer
this repo is wrong

2021-12-21 09:56 UTC, stoneshi-yunify commented on src/main/pvc-autoresizer/Chart.yaml
> +  - https://github.com/topolvm/pvc-autoresizer
should use kubesphere instead of topolvm

2021-12-21 09:56 UTC, stoneshi-yunify commented on src/main/pvc-autoresizer/Chart.yaml
> +version: 0.3.2
should start from 0.1.0

2021-12-23 05:47 UTC, stoneshi-yunify reviewed
/lgtm

2021-12-27 02:02 UTC, f10atin9 commented
/cc @zheng1

2021-12-27 02:07 UTC, zheng1 commented
/approve

2021-12-27 08:23 UTC, zheng1 commented
@xyz-li PTAL at this https://github.com/kubesphere/helm-charts/pull/205/checks

2021-12-27 08:23 UTC, merged